title: Kession
description: Software Developer
author: Kession
post_author: Kession
logo: /img/avatar.png
github: https://github.com/xiaoxunnn
about: Software Developer
mail: "xiaoxunnn@hotmain.com"

baseurl: ""
url: "https://xiaoxunnn.github.io"

allowsearch: false

analytics:
  google: UA-110214503-1
disqus:
  name: Kession

share:
  twitter_username: xiaoxunnn


enableTags: true
tagarray: []

excerpt_separator: "<!--more-->"
paginate: 35
per_page: 60
paginate_path: "/blog/page:num/"
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   math_engine: mathjax
gems: [jekyll-paginate, jekyll-gist]

# Content Collection
collections:
  articles:
    output: true

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Kession"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "Kession"
      permalink: "/article/:title.html"
